language: go
go:
    - "1.8.1"
env:
    global:
        - SSH_KEY="id_rsa"
        - GIT_NAME="Guilherme Pedrosa"
        - GIT_EMAIL="guilherme.pedrosa@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="code"
	- TEMP_DIR=$(sudo mktemp -d /tmp/$REPO_NAME.XXXX)
before_script:
  - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
  - go get -u -v github.com/spf13/hugo
script:
  - git submodule init
  - hugo
after_success:
  - chmod a+x ./scripts/deploy.sh
  - ./scripts/deploy.sh
