dist: xenial
sudo: required
language: go
go:
  - master
env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="Guilherme Pedrosa"
    - GIT_EMAIL="guilherme.pedrosa@gmail.com"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="code"
    - TEMP_DIR=$(sudo mktemp -d /tmp/$REPO_NAME.XXXX)
install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
script:
  - hugo
after_success:
  - chmod a+x ./scripts/deploy.sh
  - ./scripts/deploy.sh
